### PR TITLE
Add support for kotlin [WIP]

### PR DESCRIPTION
**Pull request by 4brunu**
Don't merge this yet.

This adds preliminary support for Kotlin but there are some missing peaces yet.

The current status of this PR is:
- [X] Support kotlin language
- [X] packages
- [X] parcelable
- [X] Import kotlin types
- [X] Import class references
- [X] generate files in directories that matches the packages
- [X] generate directories that matches the packages

### CODE REVIEW

**Comment by 4brunu** [comment]
@hebertialmeida Hey, this PR is almost finished but I think I need your help in the remaining steps.

The Kotlin files need to be generated in a directory that matches the package, so one class with the package com.github.hebertialmeida.modelgen needs to be generated with the path com/github/hebertialmeida/modelgen.
I tried to implement this, but since I don't know the project very well, It's a bit hard for me.
Can you implement this please?

~~Another point that may or may not be improved is the class reference.~~
~~This is working in the current state of the PR, but it's not my preferred way of doing this.~~
~~In Kotlin when you reference a class that is not in the same package as the current one, you need to import it.~~
~~Here is an example of what I'm saying:~~
```kotlin
import java.util.Date
val date: Date
```

~~Another way of doing this, it's by reference the class using the full path, package and class like, like in the following example:~~
```kotlin
val date: java.util.Date
```
~~Personally I prefer the first approach because it's easier to read, but the second one was easier to implement, because this way the imports aren't needed.~~
~~What do you think about this?~~

I was able to implement the second approach.
Do you prefer the first or the second?

**Comment by hebertialmeida** [comment]
I think your approach for packages is really great! Do you think that it should cover most cases of types?

Regarding the generation path, I was thinking, do you think that the spec JSON file should also follow the generation folder structure or it can be flat as it is today?

I ask that because I think we should find a common-sense between both platforms while keeping it flexible at the same time.

**Comment by 4brunu** [comment]
> I think your approach for packages is really great! Do you think that it should cover most cases of types?

The basic types are more or less covered, we can try to add more like `Set`, or others if you remember more.
Despite this, one thing that can be a bit harder to support is external dependencies.
If you want to support depending on handwritten classes, we may need to change the json files to declare external classes with the class name and package.
But maybe that can be a future improvement.
What do you think?

> Regarding the generation path, I was thinking, do you think that the spec JSON file should also follow the generation folder structure or it can be flat as it is today?

The correct way of doing this in Kotlin would be generate the folder structure, otherwise the IDE will show a warning because the package doesn't correspond with the folder structure.

**Review by hebertialmeida — APPROVED** [review]
Tested and all seems to be working good to me!

**Pull request merged**
